# Generated by Django 3.2.25 on 2025-06-17 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_alter_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guess',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='guess',
            name='attempt_times',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='guess',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='history',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='history',
            name='total_attempts',
            field=models.IntegerField(default=1),
        ),
    ]
