# Generated by Django 3.2.25 on 2025-06-17 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_auto_20250617_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='total_attempts',
            field=models.IntegerField(default=0),
        ),
    ]
